name: Lughtboxes
version: ${project.version}
main: net.lostfables.lughtboxes.Lughtbox
api-version: 1.13
authors: [LughGK]
description: A Configurable Set of Rewards
website: lostfables.net
depend: [Tythan]
commands:
  vote:
    description: Brings up the voting menu
    usage: |
      /<command> [set|add|remove] [coins|premcoins] [player] [value]
    permission: lughtboxes.vote
    permission-message: You do not have permission to access this.
permissions:
  lughtboxes.vote:
    description: Allows the use of the Vote command to access the menu
    default: not op
  lughtboxes.staff:
    description: Allows lughtbox staff commands
    default: op