name: Lughtboxes
version: ${project.version}
main: net.lostfables.lughtboxes.Lughtboxes
api-version: 1.13
authors: [LughGK]
description: A Configurable Set of Rewards
website: lostfables.net
depend: [Tythan]
commands:
  vote:
    description: Brings up the voting menu
    usage: |
      /<command> [set|add|remove] [coins|premcoins] [player] [value]
    permission: lughtboxes.vote
    permission-message: You do not have permission to access this.
  lughtbox:
    description: Manage lughtboxes
permissions:
  lughtboxes.staff:
    description: Allows Lughtboxes staff commands
    default: op
  lughtboxes.vote:
    description: Allows use of Lughtboxes vote command
